### ISSUE TITLE
Will janrain support pods ?

### ISSUE THREAD

**Issue by keithyaupingyee** [janrain/jump.ios#10]
As title and thanks

**Comment by jlmendezbonini** [comment]
Any updates on this?  CocoaPods would be a very welcomed addition.

**Comment by zgeorge** [comment]
Having a Pod take care of updates would be awesome!

**Comment by larryaasen** [comment]
I just created a pull request for a podspec file to support CocoaPods.

**Comment by jlmendezbonini** [comment]
Thanks @larryaasen for creating pull request #21

**Comment by brentnewton** [comment]
Based on the merging in of pull request #21, I am closing this issue.
