### ISSUE TITLE
Import UIKit and do not rely on the prefix file to do it

### ISSUE THREAD

**Issue by sarbogast** [janrain/jump.ios#22]
When you try to import the JUMP library in a brand new XCode project now, since the prefix file is not created by XCode anymore, and UIKit is not imported by default, you need to add import statement for UIKit to all the header files that depend on it, especially those that use the UIApplication class. In the meantime, I have worked around this issue by creating my own prefix file but your library will be easier to integrate if you do the imports yourselves.

**Comment by Limeberg** [comment]
This is still an issue and should be fixed soon though it is annoying to work around it yourself. Some of the header files that depend on UIKit to be imported are JRNativeAuth, JRActivityObject etc.

**Comment by pbjanrain** [comment]
Thank you for your feedback.  We will update the documentation for the next release to recommend the creation of the prefix file.

An example prefix file is found in the SimpleCaptureDemo app (https://github.com/janrain/jump.ios/blob/master/Samples/SimpleCaptureDemo/SimpleCaptureDemo/SimpleCaptureDemo-Prefix.pch) but I don't see it documented as a requirement.

**Comment by pbjanrain** [comment]
This issue was addressed in the 4.0 Release.
