### ISSUE TITLE
Apple rejected app during review

### ISSUE THREAD

**Issue by jhermsdorf** [janrain/jump.ios#24]
Hi,

we received the notification from Apple today that our app was rejected, because the Google Sign-In opens Safari Browser instead of a WebView within the app, when the native Google+ app is not installed on a user's device.
However, we are not the only ones facing this problem of being rejected by Apple:
https://code.google.com/p/google-plus-platform/issues/detail?id=900
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/37

While Google reacted in the meantime and released a new version 2.0 of their Sign-In SDK (https://code.google.com/p/google-plus-platform/issues/detail?id=900#c109) this version is not yet supported by the Janrain Jump SDK. 
Therefore we only have 2 choices right now:
1. Drop Google Sign-In from our app, so we get approved by Apple.
2. Hack and fix the Janrain SDK ourselves, so it works like Apple want's it.

Would be great if Janrain could release an updated version of the Jump SDK as soon as possible, which uses the new Google Sign-In SDK 2.0 instead of the Google+ SDK.

Cheers

**Comment by pbjanrain** [comment]
This issue was addressed in the 4.0 Release.
