### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by tsipinio** [janrain/jump.ios#25]
There are many deprecation warnings related to UIActionSheet:
'UIActionSheet' is deprecated: first deprecated in iOS 8.3 - UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead

**Comment by pbjanrain** [comment]
Thank you for your feedback.  We are aware of these warnings (they relate to the multiple Twitter account selection with native Twitter authentication).  In the next release of the SDK we hope to have this issue resolved as we will be changing the way the SDK works with native authentication providers.

If you are in immediate need of supporting this functionality you can branch the SDK and replace the calls to the UIActionSheet with calls to UIAlertController as outlined here:  

https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActionSheet_Class/index.html

Thank you again for your feedback.

**Comment by pbjanrain** [comment]
This issue was addressed in the 4.0 Release.
