### ISSUE TITLE
Does JUMP for iOS have a pod?

### ISSUE THREAD

**Issue by chappejw** [janrain/jump.ios#27]
Does this project have a cocoapod? if not, has anyone considered moving this project to a pod?

**Comment by pbjanrain** [comment]
There is one but it appears it did not get updated in the last revision.  We will try to get this updated in the next maintenance release.

If you would like to you can manually update lines 7 and 12 of this file and give it a try:
https://github.com/janrain/jump.ios/blob/master/Janrain.podspec

**Comment by chappejw** [comment]
Thanks for the quick reply. I will consider this for next iteration using this library.

**Comment by jeremymankin** [comment]
Hi, Was this done or do I have to still download all the files? :(

**Comment by pbjanrain** [comment]
I just updated the .podspec  - please let me know if you have any issues.  Sorry for the delay.

**Comment by jeremymankin** [comment]
Hey @pbjanrain Sorry for not getting back to you sooner. Getting some issues with the pod install.

```MANKIN-J-MAC:marvel-unlimited-ios jmankin$ pod install
Analyzing dependencies
Fetching podspec for `Haneke` from `Haneke/`
Pre-downloading: `Janrain` from `https://github.com/janrain/jump.ios.git`, branch `v4.0.0`

[!] Error installing Janrain
[!] /usr/local/bin/git clone https://github.com/janrain/jump.ios.git /var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160823-98542-1ybzhwr --template= --single-branch --depth 1 --branch v4.0.0

Cloning into '/var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160823-98542-1ybzhwr'...
warning: Could not find remote branch v4.0.0 to clone.
fatal: Remote branch v4.0.0 not found in upstream origin```

**Comment by jeremymankin** [comment]
Used:
    pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :branch => 'v4.0.0'

**Comment by jeremymankin** [comment]
Hi Paul, having some issues here. Did a pod install and got this:

Analyzing dependencies
Fetching podspec for `Haneke` from `Haneke/`
Pre-downloading: `Janrain` from `https://github.com/janrain/jump.ios.git`, tag `v4.0.0`

[!] Error installing Janrain
[!] /usr/local/bin/git clone https://github.com/janrain/jump.ios.git /var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160824-98011-15lddxf --template= --single-branch --depth 1 --branch v4.0.0

Cloning into '/var/folders/1h/nb_v8jqj19s144xs_l_wfp9h62ndbd/T/d20160824-98011-15lddxf'...
warning: Could not find remote branch v4.0.0 to clone.
fatal: Remote branch v4.0.0 not found in upstream origin

**Comment by jeremymankin** [comment]
Am I missing something: (from our Podfile)

pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => 'v4.0.0'

**Comment by pbjanrain** [comment]
Nope - looks like I tagged the release wrong.  Sorry about that.  I updated the Podfile to look for the correct tag:
pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => '4.0.0'

**Comment by jeremymankin** [comment]
Thanks. That seemed to work 👍
