### ISSUE TITLE
Version 5.0.0 Doesn't work as Cocoapod

### ISSUE THREAD

**Issue by cfis** [janrain/jump.ios#29]
With version 5.0.0, the file JROpenIDAppAuthGoogle.m does not compile since it requires "AppDelegate.h"  Since this is a pod, it has no access to the AppDelegate.h of the application requiring the pod.

**Comment by pbjanrain** [comment]
Sorry about that.  Can you try the latest 5.0.1 release.  I tested it with Cocoapods but I am not a regular user of Cocoapods so it would be nice to get some additional verification.

Please make sure to read the upgrade guide - if you started upgrading to v5.0.0 then there will be some things that will need to be undone.

**Comment by cfis** [comment]
Cool thanks!  Will give it a go.

**Comment by klam-networkten** [comment]
Hi there,

5.0.1 does not compile properly either.

JROpenIDAppAuthGoogle.m:28

#import "AppAuth.h"

But AppAuth.h is not found within the pod.
