### ISSUE TITLE
Error: "'AppAuth.h' file not found" in JROpenIDAppAuthGoogleDelegate.h when using CocoaPods

### ISSUE THREAD

**Issue by ashokds** [janrain/jump.ios#33]
This issue can be reproduced easily with this sample project: https://github.com/ashokds/janrain-5.0.3-pod-issue
Follow instructions in readme file. All I did was create a new project --> perform 'pod init' --> setup Podfile to use Jainrain along with other pods --> 'pod install' --> build to notice the error.

---
Using cocoapods 1.1.1 to integrate Janrain 5.0.3 as following: 

`pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => '5.0.3'`

And it results in following compiler error:
`'AppAuth.h' file not found` in `JROpenIDAppAuthGoogleDelegate.h`

Lexical or Preprocessor Issue Group
```
.../Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuthGoogleDelegate.h:28:9: 'AppAuth.h' file not found
.../Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuth.m:29:9: In file included from
.../Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuth.m:29:
```

Perhaps it's better to change this import statement: `#import "AppAuth.h"` to: `#import <AppAuth/AppAuth.h>`

Details: 
Also, according to the following upgrade guide (https://github.com/janrain/jump.ios/blob/master/Docs/Upgrade%20Guide.md): it assumes that project is using static frameworks instead of dynamic frameworks. Following is the podfile with `use_framework!` option.
```
platform :ios, '8.0'
target 'XYZApp-v3' do
    use_frameworks!

    #other pods 
    pod 'GTMAppAuth'
    pod 'AppAuth'
    pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => '5.0.3'
end
```

**Comment by pbjanrain** [comment]
You need to make sure that you include the OpenID AppAuth pod in before the Janrain pod.

https://github.com/janrain/jump.ios/blob/master/Docs/Upgrade%20Guide.md#upgrading-from-any-version-prior-to-v500-to-v501-or-greater

http://openid.github.io/AppAuth-iOS/
```pod 'AppAuth'```

I think that will resolve the issue you are seeing.

**Comment by ashokds** [comment]
hi @pbjanrain,

Yes, I did see that suggestion to add `pod 'AppAuth'`. 
I was looking at other guides, corrected the upgrade guide link in question above.  

Thanks for a prompt reply.

**Comment by pbjanrain** [comment]
Thanks - I'll update the podspec.

**Comment by pbjanrain** [comment]
Looks like ```#import <AppAuth/AppAuth.h>``` doesn't work in the non-CocoaPods implementation.

**Comment by ashokds** [comment]
Having `pod 'AppAuth'` in the podfile doesn't resolve it. Performed cleanup and fresh build --> and getting the same error.

Also tried adding `AppAuth.framework` in the `Linked Frameworks and Library` section of the main app target.

**Comment by pbjanrain** [comment]
I'm not sure what to recommend.  You're the first customer to report this and previous testing indicated it was working.  Perhaps just add the the folder where CocoaPods placed the AppAuth code to the header search path in your Build Settings?

**Comment by pbjanrain** [comment]
But if you figure something out please feel free to submit a pull request and I'll review and test it as soon as I have time.

**Comment by ashokds** [comment]
I am experimenting with adding following to "Header Search Paths":
`"$(SRCROOT)/Pods/AppAuth"`

According to this link (https://github.com/facebook/react-native/pull/12089/files#diff-66230b3e029caa37b0fbdc8cbd47f4abR50), this might resolve issue associated with "Header Search Paths". 
`ss.pod_target_xcconfig  = { "HEADER_SEARCH_PATHS" => "$(PODS_TARGET_SRCROOT)/AppAuth" }`

**Comment by pbjanrain** [comment]
I couldn't see a way in CocoaPods to add the recursion option to the search path you may also need to add:
```
ss.pod_target_xcconfig = { "HEADER_SEARCH_PATHS" => "$(PODS_TARGET_SRCROOT)/AppAuth/Source" }
```
and/or
```ss.pod_target_xcconfig = { "HEADER_SEARCH_PATHS" => "$(PODS_TARGET_SRCROOT)/AppAuth/Source/iOS" }``

**Comment by ashokds** [comment]
Hi @pbjanrain, Added a sample project to help debug this issue. Also updated the original description above.
---
This issue can be reproduced easily with this sample project: https://github.com/ashokds/janrain-5.0.3-pod-issue
Follow instructions in readme file. All I did was create a new project --> perform 'pod init' --> setup Podfile to use Jainrain along with other pods --> 'pod install' --> build to notice the error.

**Comment by ashokds** [comment]
So far I haven't forked jump.ios to experiment with different ss.pod_taret_xcconfig settings in the podspec. I was hoping to resolve this error by applying other fixes (e.g. modifying "header search path" in target projects, etc).

**Comment by ashokds** [comment]
@pbjanrain, #34 addresses the header search path issue. I created a PR, please have a look.

**Comment by pbjanrain** [comment]
Looks great - thanks for your help with this.  I have updated the podfile and the Upgrade Guide documentation.  We have a slightly convoluted update process for this repo so I had to update our internal repo first and then push a new branch to this repo.  Your changes should now be visible in the main branch.

**Comment by ashokds** [comment]
Nice. I've pointed my app to 'master' instead of tag. 
`pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :branch => 'master'`
Builds are passing. 
Thanks for a quick turnaround.
