### ISSUE TITLE
Exception: Could not load NIB in bundle with name JRWebViewController

### ISSUE THREAD

**Issue by ashokds** [janrain/jump.ios#36]
I have integrated Janrain 5.0.3 with cocoapods with a project that utilizes "use_framework!". It's the next step after resolving #33. 

Following are part of pods/Janrain/Resources/xibs/en.lproj/* 
* JRProvidersController.xib
* JRUserLandingController.xib
* JRWebViewController.xib

These xibs aren't getting loading and an exception is thrown after following is invoked.
`[JREngage showAuthenticationDialogForProvider:@"twitter"];`

Sample podfile:
```
platform :ios, '8.0'
target 'appname-v2' do
    use_frameworks!

    #other pods 
    pod 'GTMAppAuth'
    pod 'AppAuth'
    pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :branch => 'master'
end
```

```
   pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :branch => 'master'

   CocoaPods : 1.1.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2.1 (8C1002)
```

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/xx.yy/Library/Developer/CoreSimulator/Devices/E11E5A14-9652-4209-AE2C-CE07B6828288/data/Containers/Bundle/Application/682096D4-9187-4BEF-9AC6-E3146BC5DDDF/appname-v2.app> (loaded)' with name 'JRWebViewController''
2017-03-29 13:50:38.484 appname-v2[53965:2742626] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/xx.yy/Library/Developer/CoreSimulator/Devices/E11E5A14-9652-4209-AE2C-CE07B68282D8/data/Containers/Bundle/Application/682096D4-9187-4BEF-9AC6-E3146BC5DADF/appname-v2.app> (loaded)' with name 'JRWebViewController''
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000115630d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000114c9c21e objc_exception_throw + 48
	2   CoreFoundation                      0x000000011569a2b5 +[NSException raise:format:] + 197
	3   UIKit                               0x000000011296ebd2 -[UINib instantiateWithOwner:options:] + 507
	4   UIKit                               0x00000001127029c5 -[UIViewController _loadViewFromNibNamed:bundle:] + 386
	5   UIKit                               0x00000001127032e7 -[UIViewController loadView] + 177
	6   UIKit                               0x000000011270361c -[UIViewController loadViewIfRequired] + 201
	7   UIKit                               0x0000000112703e70 -[UIViewController view] + 27
	8   UIKit                               0x00000001127521fa -[UINavigationController preferredContentSize] + 198
	9   UIKit                               0x00000001126e616e -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	10  UIKit                               0x00000001126e1f98 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 111
	11  UIKit                               0x000000011256e62f _runAfterCACommitDeferredBlocks + 320
	12  UIKit                               0x000000011255b273 _cleanUpAfterCAFlushAndRunDeferredBlocks + 566
	13  UIKit                               0x000000011258c746 _afterCACommitHandler + 176
	14  CoreFoundation                      0x00000001155d5267 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	15  CoreFoundation                      0x00000001155d51d7 __CFRunLoopDoObservers + 391
	16  CoreFoundation                      0x00000001155b9f8e __CFRunLoopRun + 1198
	17  CoreFoundation                      0x00000001155b9884 CFRunLoopRunSpecific + 420
	18  GraphicsServices                    0x0000000117a1ba6f GSEventRunModal + 161
	19  UIKit                               0x0000000112561c68 UIApplicationMain + 159
	20  appname-v2                       0x000000010b09450f main + 111
	21  libdyld.dylib                       0x0000000115c3068d start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
2017-03-29 13:50:38.486358 appname-v2[53965:2748653] [] __tcp_connection_write_eof_block_invoke Write close callback received error: [89] Operation canceled
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ashokds** [comment]
@pbjanrain, any help with this?

**Comment by pbjanrain** [comment]
Seems like maybe these files didn't get included?

https://github.com/janrain/jump.ios/tree/master/Janrain/JREngage/Resources/xibs

Did CocoaPods download them?

**Comment by ashokds** [comment]
Just got back from a meeting. Yes, cocoapods did download them. JRWebViewController.xib is present under regular pods/Janrain/Resources/xibs/* & pods/Janrain/Resources/*.

![screen shot 2017-03-29 at 3 11 57 pm](https://cloud.githubusercontent.com/assets/17131511/24479012/2b956108-1492-11e7-8768-1eaea2ac2e7c.png)

**Comment by pbjanrain** [comment]
Maybe try cleaning your XCode project and clearing the Simulator contents?

I would think that if the files are in your project they should be getting compiled into the app.

Otherwise, could you please open a Janrain Support ticket through the Janrain Support portal (support.janrain.com) and provide more details, including:

- The Capture application you are testing against.
- The API Client you are testing with.
- The full log files including all the log data from the time the application is started to after any errors are thrown.
- The stack trace from when the error is thrown.

Please reference this Github issue in the ticket and ask them to escalate to engineering for analysis.

**Comment by ashokds** [comment]
I can't use my usual dashboard.janrain.com user info to login to support.janrain.com. In order to report a ticket via support.janrain.com, it seems, I will need a separate Janrain account and might take some time to get it. 

I guess, in the meantime, I'll try normal integration for Janrain 5.0.3 instead of cocoapods.

**Comment by ashokds** [comment]
I tried resetting simulator and whole-cleanup of project & derived data. It's the same result.

**Comment by ashokds** [comment]
@pbjanrain, Open support ticket: https://janrain.atlassian.net/browse/CSP-32332

**Comment by pbjanrain** [comment]
Did some Googling, are you writing in Swift?

From: https://guides.codepath.com/ios/CocoaPods
> Consuming Objective-C Libraries from Swift

> With the use_frameworks! directive, you can also consume Objective-C libraries from your Swift code without the need of a bridging header anymore. You'll be able to directly import the framework (i.e. import AFNetworking).
> 
> Potential Issue: Unfortunately, all Objective-C Pods haven't been updated to work with the new dynamic frameworks behavior. You might come across certain Objective-C Pods that no longer build after adding the use_frameworks! directive. In these cases you can either not use the use_frameworks! directive (you'll now need to create a bridging header) or manually edit the offending Pod to help it find the headers (as done in the linked issue).

The Janrain mobile libraries are unfortunately not set up to work as dynamic frameworks.  If you feel that this is something that needs to be addressed you will have to work through the Account Management team to see if this is something that the Product Management team can prioritize.

**Comment by ashokds** [comment]
Current app is in Objective and uses cocoapods v1.1.1. 

Some of the other 3rd party frameworks are integrated as dynamic framework with use_framework! they have been part of a few previous releases and changing that integration would ask for a complete regression around core features.

**Comment by pbjanrain** [comment]
This issue has been noted in our internal system and the Product Management team will have to manage the scheduling of any work to resolve this issue.
You may choose to escalate support on this issue through the Janrain support portal at https://support.janrain.com
