### ISSUE TITLE
Janrain.framework/buttons: Directory not empty error

### ISSUE THREAD

**Issue by Harinder** [janrain/jump.ios#38]
Hi, 
   when using with cocoa-pods (janrain v 5.0.3), this is the compile time error we get. 

error: remove /Users/h*******/Library/Developer/Xcode/DerivedData/*********-wokg/Build/Products/Debug-iphonesimulator/Janrain/Janrain.framework/buttons: Directory not empty

  Looks like the issue is because there are duplicate folder references with the same name. Here is the snapshot:

<img width="288" alt="screen shot 2017-06-01 at 4 56 05 pm" src="https://cloud.githubusercontent.com/assets/279475/26705489/5d4477da-46eb-11e7-9645-1c858fd8529c.png">

**Comment by pbjanrain** [comment]
This issue has been noted in our internal system and the Product Management team will have to manage the scheduling of any work to resolve this issue.

You can always submit a pull request with your suggested changes.  This may expedite the process of getting the change into an official release.

You may also choose to escalate support on this issue through the Janrain support portal at https://support.janrain.com
