### ISSUE TITLE
SDK has 35 build warnings for deprecated iOS APIs

### ISSUE THREAD

**Issue by randyhill** [janrain/jump.ios#39]
I'm trying to eliminate compile time warnings from my iOS project. Long-standing warnings can obscure new problems and lead to lower code quality. The warnings in this case also indicate the potential danger that a future iOS version will break the Janrain iOS SDK.

My app is built as a Swift project. I include the Jainrain SDK directly. It's been functional and used in the app for at least a year. I just updated to the 5.0.5 SDk in hopes the warnings would be eliminated, but they still exist.  Specific include

> /Janrain/JREngage/Classes/JRUserInterfaceMaestro.m:459:12: 'UIPopoverController' is deprecated: first deprecated in iOS 9.0 - UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.

> /Janrain/JRConnectionManager/JRConnectionManager.m:45:62: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

> /Janrain/JRConnectionManager/JRConnectionManager.m:198:13: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)

> /Janrain/JRConnectionManager/JRConnectionManager.m:260:22: 'sendAsynchronousRequest:queue:completionHandler:' is deprecated: first deprecated in iOS 9.0 - Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h

> /Janrain/JREngage/Classes/JRWebViewController.m:350:13: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead

**Comment by pbjanrain** [comment]
Unfortunately, our libraries need to maintain a broad iOS version support range.  Many of these issues might break compatibility with older version of iOS.  If you change your os support level to a lower version these warnings may go away.

You are welcome to make your own branch of the libraries and update these issues if they are that important to you.

If you feel this is not a suitable answer you may open a support ticket through your Janrain representative at http://support.janrain.com and request escalation to our Product Management team through your Janrain Account Manager.

Thank you

**Comment by randyhill** [comment]
https://developer.apple.com/support/app-store/

As of June 5th, 97% of iOS users are on iOS 9 or later. The remaining 3% does not represent active buyers of apps. If you updated and released a new version of the SDK for iOS 9+, you could eliminate all of the deprecation warnings. You could still provide version 5.0.5 of the SDK for clients who somehow need to support nearly extinct hardware and OS versions.

And I think this would be a significant benefit to Jainrain itself. The SDK already has a reputation as a problem among developers I have spoken to. I would not tolerate my fellow developers checking in code that produces warnings, especially deprecation warnings, in our projects. The Jainrain SDK is lowering code quality standards in hundreds if not thousands of projects that depend upon it.  Removing these warnings would be a good step to reassure developers that the Jainrain SDK is professional, trustworthy code.

One last question. Have you tested in iOS 11 yet?
