### ISSUE TITLE
Xcode 9's new build system can't build projects using janrain sdk

### ISSUE THREAD

**Issue by randyhill** [janrain/jump.ios#45]
Looks like Xcode 9s new improved build system doesn't like duplicate file names, even if in different paths. To try the new build system, open your projects workspace, go to the file menu, select Workspace Settings and set to new build system.

The errors I get are for the files

JREngage/Resources/en.lproj/Localizable.strings 
JRCapture/Resources/en.lproj/Localizable.strings

**Comment by pbjanrain** [comment]
Thank you for bringing this to our attention.  Since the new build system is still in "preview" we will make sure to address this in a future release.
