### ISSUE TITLE
App is crashing on presenting Facebook / Twitter Authentication screen

### ISSUE THREAD

**Issue by NishanthMurugan** [janrain/jump.ios#48]
Have configured the Janrain via cocoa pod

```
pod 'AppAuth'
pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => '5.1'
```

when trying to present the Facebook or twitter social  authentication screen, app is crashed with following error

**Could not load NIB in bundle (loaded)' with name 'JRWebViewController''**

The code  which used to present the Social authentication screen is 

```
self.customUi = @{kJRModalDialogPresentationViewController : self};
 [JRCapture startEngageSignInDialogOnProvider:@"facebook" withCustomInterfaceOverrides:self.customUi
                                         forDelegate:nil];
```

**Comment by pbjanrain** [comment]
Can you please open a support ticket request referencing this post at https://support.janrain.com.

Please include the FULL XCode debug console log file from the moment you start the application all the way through until you have acknowledged any error dialogs.  We can not proceed on this issue without the debug log file.  Do NOT post the log file contents to this public repo.

Thank you.

**Comment by NishanthMurugan** [comment]
Sure @pbjanrain  Will open a support ticket with full Xcode debug log.
