### ISSUE TITLE
JREngage does not return error if getAuthInfo for a token has failed

### ISSUE THREAD

**Issue by Ad1991** [janrain/jump.ios#50]
JREngage method
```
+ (void)getAuthInfoTokenForNativeProvider:(NSString *)provider
                                withToken:(NSString *)token
                           andTokenSecret:(NSString *)tokenSecret
                          andEngageAppUrl:(NSString *)engageAppUrl
```

does not return error back to application if the authInfo request returns error:

```
Native authentication error: Error Domain=JREngage.ErrorDomain Code=203 "(null)" UserInfo={result={
    err =     {
        code = 1;
        msg = "token does not match the facebook application registered with Janrain";
    };
    stat = fail;
}, error=null}  
```

The issue seems to be at this [line](https://github.com/janrain/jump.ios/blob/176a89d4f8a2e66d57f23cb66c4413aba6d28755/Janrain/JREngage/Classes/JREngage.m#L318) where the error is only logged and is not returned to JRSessionData delegates

**Comment by pbjanrain** [comment]
Thanks for your well written comment and pull request.  I'll try and find some time to review it and merge it in.  Hopefully, within the next week.

**Comment by pbjanrain** [comment]
This has been added to our next release.  Closing this commit as we have a slightly convoluted release process for this repo.
