### ISSUE TITLE
Cocoapods #IFDEF Breaks Cordova Project

### ISSUE THREAD

**Issue by cthos** [janrain/jump.ios#52]
Hi there 👋 .

I'm currently integrating the Jump libraries via a custom Cordova Plugin, which installs Jump as a Pod Dependency, at tagged version 5.1.1.

Unfortunately, this commit (and the one preceding it) e1ec17b68eae43db8a069e92713e674c36a548b9 , causes the cordova build to break with the following error:

```
In file included from /Users/cthos/Documents/Code/Redacted/platforms/ios/Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuthGoogle.m:26:
In file included from /Users/cthos/Documents/Code/Redacted/platforms/ios/Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuthGoogle.h:28:
/Users/cthos/Documents/Code/Redacted/platforms/ios/Pods/Janrain/Janrain/JREngage/Classes/JROpenIDAppAuthGoogleDelegate.h:29:13: fatal error: 'AppAuth/AppAuth.h' file not found
    #import <AppAuth/AppAuth.h>
            ^~~~~~~~~~~~~~~~~~~
```

If I manually change the `#ifdef` lines back to simply `#import "AppAuth.h` it works and builds from the command line just fine.

Oddly, I don't get the error if I'm building directly in XCode, which makes me suspect some sort of build flag that Cordova's injecting, but I'm not sure where that would be, I've had a look through all of the config and it appears to be okay.

Any ideas?

**Comment by pbjanrain** [comment]
Sorry we no longer provide support for Cordova and don't have anyone with much experience with it either.

**Comment by cthos** [comment]
Cool, thanks for the reply - I'll continue poking at it. 👍 - FWIW I'm pretty sure it's a subtle difference in the header search paths.

**Comment by pbjanrain** [comment]
Yeah - we had to add that in for Cocoapods compatibility.  Are you including the AppAuth pod in your Cordova project?  That is why that ifdef is there.  The include was messing up regular cocoapods installs.

**Comment by cthos** [comment]
Yep, the plugin.xml reference looks like this:

```
